### ISSUE TITLE
It reports that it fails after 0 tries, even through it tried the test...

### ISSUE THREAD

**Issue by SimonRichardson** [puffnfresh/bilby.js#6]
This is more a question than anything else... 

Considering the check property in test.js will report that 'Failed after 0 tires: ...' when a test has failed, shouldn't that be 'Failed after 1 tries: ...'[1] as it has tried to run the test?

I would do a pull request, but I'm playing around with bilby atm, but thought it would good to report it at least.
https://github.com/SimonRichardson/bilby.js/commit/0d49a4d7b0441e8924058434c791e9e81801946d

[1] ignoring the '1 try' vs '1 tries' issue

**Comment by puffnfresh** [comment]
Yeah, you're right! Thanks. I cherry-picked your commit and gave you access to this repo.

I also like the do.js removal. That's the direction I'm going in, pulling bilby.js apart so I can put it back together again. This is the idea behind:
- do.js: https://github.com/puffnfresh/fo
- Constructors magic from helpers.js: https://github.com/puffnfresh/daggy

bilby.js will hopefully go into the direction of "a useful combination of a heap of separate libraries" - good idea?

> [1] ignoring the '1 try' vs '1 tries' issue

Thanks :smile:

**Comment by SimonRichardson** [comment]
One thing I really like about bilby.js is the fact that it has the core things there (either, option, trampoline, etc) - I'd like to add promises and tuples to it and maybe list (nil, cons). Then you could build off that, so do.js can use bilby.js if required (although it currently doesn't). 

The issue I've found with having to many git repos all referencing the same project is how you manage them. Submodules become a nightmare if you don't set them up correctly (aligning to tags vs commits). If you change one part of a library that relies on other parts then keeping the dependencies updated becomes a bit of a headache.
